# Generated by Django 3.2.4 on 2021-06-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField()),
                ('dime', models.IntegerField()),
                ('nickel', models.IntegerField()),
                ('penny', models.IntegerField()),
                ('one_dollar', models.IntegerField()),
                ('five_dollars', models.IntegerField()),
                ('ten_dollars', models.IntegerField()),
                ('twenty_dollars', models.IntegerField()),
                ('fifty_dollars', models.IntegerField()),
                ('one_hundred_dollars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Saver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image_url', models.ImageField(upload_to='')),
                ('goal_amount', models.IntegerField()),
                ('created_on', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('sound_effect', models.URLField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencykidzapi.currency')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencykidzapi.saver')),
            ],
        ),
        migrations.CreateModel(
            name='DepositEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('sound_effect', models.URLField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencykidzapi.currency')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencykidzapi.saver')),
            ],
        ),
    ]
