# Generated by Django 3.2.4 on 2021-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencykidzapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='dime',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='nickel',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='penny',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='quarter',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
