# Generated by Django 3.2.4 on 2021-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencykidzapi', '0004_auto_20210614_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='dime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='nickel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='penny',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='quarter',
            field=models.IntegerField(),
        ),
    ]
