# Generated by Django 3.2.4 on 2021-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencykidzapi', '0005_auto_20210621_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saver',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
